--- #YAML:1.0
name:                Helix-Driver-User-Basic
version:             0.02
abstract:            Helix Framework basic user driver.
license:             ~
author:              
    - Anton Belousov <abel@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Helix:                         0.02
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
